### ISSUE TITLE
Alpine Version

### ISSUE THREAD

**Issue by f4bio** [ubergarm/openresty-nginx-jwt#1]
hi there  
  
the [TODO in your README.md](https://github.com/ubergarm/openresty-nginx-jwt/blob/master/README.md#todo) is fixed by using `openresty/openresty:alpine-fat` instead of the base alpine version (see [explanation](https://github.com/openresty/docker-openresty#luarocks))

I ran into the exact same problem yesterday. I had to customize your work further, resulting in a [different project](https://github.com/f4bio/docker-openresty-jwt). I think my changes wouldn't fit your project's intentions as they tackle a few more problems I ran into during development.
But, I could of course create some PRs, if you want to?

Anyhow.... TLDR: use `openresty/openresty:alpine-fat` instead of "openresty/openresty:alpine"

**Comment by ubergarm** [comment]
Finally working on this now. Just about a year later.. :) Thanks for finding the alpine-fat flavor!

Took the size down from ~517MiB to ~241MiB not bad!

[60ab81fcde]
